<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No file Chosen</name>
   <tag></tag>
   <elementGuidId>c9659516-8054-465c-85f1-2431c9214220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content-wrapper']/app-driver-created-documents-upload/div/div[2]/form/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.file-input-file-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>10a7b575-0522-4ccb-ba61-7e789f8a325c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>file-input-file-name</value>
      <webElementGuid>da434ea2-9a54-49c8-a7d6-2f2cc72ac60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> No file Chosen </value>
      <webElementGuid>ed39de29-90d9-4281-b642-f436af80771c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content-wrapper&quot;)/app-driver-created-documents-upload[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ps-3 ps-md-5 document-upload&quot;]/div[@class=&quot;pt-4 document-upload-content&quot;]/form[@class=&quot;d-flex flex-column col-md-7 col-12 px-0 px-md-3 alternate-theme ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;mt-2&quot;]/div[@class=&quot;d-flex file-input&quot;]/div[@class=&quot;file-input-file-name&quot;]</value>
      <webElementGuid>9e2a9b64-0562-45cb-a1f8-7e2f5c02ccd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content-wrapper']/app-driver-created-documents-upload/div/div[2]/form/div/div/div</value>
      <webElementGuid>31cdb5b1-d920-4786-b926-b5fb4e4d777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>d8f0b9b1-13bf-43ae-8a04-ca9b98de15f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' No file Chosen ' or . = ' No file Chosen ')]</value>
      <webElementGuid>a6f0db86-74b1-48ec-9484-0489188a5a59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
