<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find</name>
   <tag></tag>
   <elementGuidId>aaea77dd-3805-4ff2-ab67-daf8e40b20e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Find' or . = 'Find')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sm-16708718021409585-4 > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sm-16708718021409585-4']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2b06dd6c-a847-4544-a312-1fcb53aeb97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#menu718105</value>
      <webElementGuid>62530b9c-c56c-46de-9af8-ae1030fea048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find</value>
      <webElementGuid>d4ab7e32-bb55-461f-9a45-aec0d8a7e446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-16708718021409585-4&quot;)/li[1]/a[1]</value>
      <webElementGuid>2360c0cc-3cb5-49a5-8977-728fa31c27e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-16708718021409585-4']/li/a</value>
      <webElementGuid>48f64261-6ce2-4b21-941c-46cbee311cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find')]</value>
      <webElementGuid>218d687c-18bb-4546-81a5-e637e2626752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List DWSP Risks'])[1]/following::a[2]</value>
      <webElementGuid>56307752-b823-4a3b-a98b-3da74171c025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Water treatment works'])[1]/following::a[3]</value>
      <webElementGuid>e6e71e11-f032-455b-8c5e-f9fd53921a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find locked'])[1]/preceding::a[1]</value>
      <webElementGuid>dd3b0d84-872f-4432-9121-6f2e0b3bf6d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New need by type'])[1]/preceding::a[2]</value>
      <webElementGuid>e120330f-2b99-4c5e-a7e7-de3ef913ef86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find']/parent::*</value>
      <webElementGuid>bc143734-b871-45fd-842c-04285b80df91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#menu718105')]</value>
      <webElementGuid>001c7fc9-b480-44b8-99d5-7cd50a60369e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>ec522214-7dc8-4f7c-ad24-7d0415533dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#menu718105' and (text() = 'Find' or . = 'Find')]</value>
      <webElementGuid>f3a4a397-678a-42bc-88dd-2ef6c065c999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
