<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_N1061521 - Dave</name>
   <tag></tag>
   <elementGuidId>330f7c1f-a84a-41a1-9679-d637f2e9c26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='RR722131:7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f2894a7-9ba7-4996-9136-d9516ea4e1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1008</value>
      <webElementGuid>2b007b87-18ce-40d0-97b2-6d7952c1ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4f95b02b-de17-4ae3-b0a1-b2b98435489c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RR722131:7</value>
      <webElementGuid>3b975a33-7b4b-47f9-9ede-387253b5a946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-golink</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>a2915d2a-cc10-4a67-85b4-9191410095a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>N106152/1 - Dave</value>
      <webElementGuid>7c25195c-3694-40f1-bd96-d4580bce3ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RR722131:7&quot;)</value>
      <webElementGuid>e5a8682c-7402-4aeb-9dd0-1b6618fadc00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='RR722131:7']</value>
      <webElementGuid>28cf3310-bcc3-4c56-b6ec-529aa2ca0afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='REP101605']/div/div[3]/div/div/div/table/tbody/tr/td/div/a</value>
      <webElementGuid>655c30a0-5ee6-47df-834f-7e702c4b391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'N106152/1 - Dave')]</value>
      <webElementGuid>5dc18299-09a5-4a11-8f21-7121bd8bc4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment Needs'])[1]/following::a[1]</value>
      <webElementGuid>8b8e778e-05be-4883-8c2f-5f99ee6698a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last Viewed Records'])[2]/following::a[2]</value>
      <webElementGuid>a763c38b-158e-4e79-869a-71966b221c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'RR722131:7', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>9e2649df-6324-4b0e-876f-50dcce2fcc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CWI Ancillaries (Valves Hydrants etc)'])[1]/preceding::a[1]</value>
      <webElementGuid>0acaaad7-fb7e-4672-85a4-b334f4763e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='N106152/1 - Dave']/parent::*</value>
      <webElementGuid>bb5b4048-69ac-4f3b-b208-f2e7763776d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[100]</value>
      <webElementGuid>b0e1d53a-f6f6-4cc6-ba5b-ec79f6431c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/a</value>
      <webElementGuid>0668a6e4-b12c-4901-add2-6348e309bda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'RR722131:7' and (text() = 'N106152/1 - Dave' or . = 'N106152/1 - Dave')]</value>
      <webElementGuid>7ddf235a-8361-4855-8dd7-141c1c541822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
