<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New need by type</name>
   <tag></tag>
   <elementGuidId>89947900-b4a7-4d91-b315-46f5e4bd3e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sm-16708718021409585-4']/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(contains(text(), 'New need by type') or contains(., 'New need by type'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e18b0e5a-a672-41cd-9841-89439bf8f984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#menu718109</value>
      <webElementGuid>4fb16579-f217-496f-89cb-a616b94b590a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[(contains(text(), 'New need by type') or contains(., 'New need by type'))]</value>
      <webElementGuid>00f21c51-8e81-4ff8-8f02-9c277786f99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath2</name>
      <type>Main</type>
      <value>id(&quot;sm-16708718021409585-4&quot;)/li[3]/a[1]</value>
      <webElementGuid>9abbab23-a71c-48a0-aec8-4acc6776cca2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-16708718021409585-4']/li[3]/a</value>
      <webElementGuid>8bd7fee3-674f-4fee-a136-96723c93a109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New need by type')]</value>
      <webElementGuid>95a4bb02-ecc5-44c6-bfe8-47894a710d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find locked'])[1]/following::a[1]</value>
      <webElementGuid>275f22bf-fc27-4176-bd16-b23b92611e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find'])[1]/following::a[2]</value>
      <webElementGuid>1aa30487-8eb8-479e-ae1a-cd795f31588a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detailed need report'])[1]/preceding::a[2]</value>
      <webElementGuid>96443d4e-7ffc-4012-9219-dfeae3e1b8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-defined reports'])[1]/preceding::a[3]</value>
      <webElementGuid>2d2d8e20-39d4-441a-aab9-6801e3a6bd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New need by type']/parent::*</value>
      <webElementGuid>2089dbcf-964b-4de8-838f-051cb9a8721c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#menu718109')]</value>
      <webElementGuid>a44e0ed5-2ca9-4f6a-9891-416e2db162c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>340d02b1-f853-4cf1-b23b-f15f22c9dd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#menu718109' and (text() = 'New need by type' or . = 'New need by type')]</value>
      <webElementGuid>d4ef0491-e7ec-4cc4-b27b-cc2da43f546c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
