<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Needs</name>
   <tag></tag>
   <elementGuidId>5f0a5412-d7cc-4d32-aa22-91e873d82aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and (contains(text(), 'Needs') or contains(., 'Needs'))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sm-16708718021409585-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sm-16708718021409585-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9343dd2b-8b2b-43c0-b5ab-bd2202ed76fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>1dffc103-6466-4223-8e48-cf657697fbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle has-submenu</value>
      <webElementGuid>fd55ba09-64f1-43ad-8a52-181d83ba68ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sm-16708718021409585-3</value>
      <webElementGuid>80586b13-8a63-406e-8705-b94c1c7e8aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51bd7917-fbb4-4bf7-9df8-3e8f9d432845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sm-16708718021409585-4</value>
      <webElementGuid>2487c322-98ff-4bb6-a4a5-763875351906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40546d9a-ca33-49ff-9b32-885d157d7b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Needs</value>
      <webElementGuid>b88560ac-76b7-46b7-94a9-26cd13c967b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-16708718021409585-3&quot;)</value>
      <webElementGuid>89a7dd2e-57c0-48a5-ad1f-b5e657c6973d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sm-16708718021409585-3']</value>
      <webElementGuid>9d917e4f-20d9-4e42-8286-d2b012e2ce12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu-navbar-collapse-1']/ul/li[2]/a</value>
      <webElementGuid>d8364ae0-87bc-4038-ba1c-756a1da1ca19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Needs')]</value>
      <webElementGuid>c1be9f4b-3562-4539-b69d-fb5626b1dc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List DWSP Risks'])[1]/following::a[1]</value>
      <webElementGuid>f370af4e-df59-486e-95a2-7491d729f387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Water treatment works'])[1]/following::a[2]</value>
      <webElementGuid>4aaff698-4974-4083-88c5-5d4c953fda30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find'])[1]/preceding::a[1]</value>
      <webElementGuid>31a8ba38-7cbf-42b0-ae84-f9a3e64ea0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find locked'])[1]/preceding::a[2]</value>
      <webElementGuid>9b96478b-9b43-439a-868f-67d3b1a17478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Needs']/parent::*</value>
      <webElementGuid>c7c0842a-58f8-4008-ae33-c9363b316cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>32aa842b-e752-430f-a254-428b7dce7a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>d0b31a57-4743-4fb9-a258-a64110b270a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'sm-16708718021409585-3' and (text() = 'Needs' or . = 'Needs')]</value>
      <webElementGuid>e19ac21c-eaf1-42bd-bb51-2f8f290bf4ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
