<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_20068713 - Security Hatch No.10 (Slave)</name>
   <tag></tag>
   <elementGuidId>499fdad9-43cf-4488-a26f-c29538060475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-25</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d7b3d81-0906-4b3d-8764-ddfe8ec2b517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a6903c54-5161-4b27-a529-04c873e8aa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>0f8b3d52-4b45-4e36-b725-df4e734a4dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-25</value>
      <webElementGuid>34334c3a-3b27-4ed1-b62f-f0ae6839424b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20068713 - Security Hatch No.10 (Slave)</value>
      <webElementGuid>295c6e8e-6b9f-4b8b-a22f-905b734d1c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-25&quot;)</value>
      <webElementGuid>91ad5b29-f48a-472a-99d0-f7c6090e50b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-25']</value>
      <webElementGuid>7d1bd9e1-4488-4efe-8729-df6ad593b825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-24']/li/div</value>
      <webElementGuid>f38e23e6-b6a9-4218-9fc6-ef3fe88c9877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CWI Ancillaries (Valves Hydrants etc)'])[4]/following::div[4]</value>
      <webElementGuid>c0586ae5-47d8-467a-8dc6-26a7f6d2295d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WWNI Sludge Treatment Facilities'])[3]/following::div[6]</value>
      <webElementGuid>f1ab3c14-1658-4e77-97b0-eccb5bab1728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20068713 - Security Hatch No.10 (Slave)']/parent::*</value>
      <webElementGuid>55c4f93d-05cf-4267-8d2e-364a69ac9fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li/div</value>
      <webElementGuid>8199dc34-eb95-417a-80b3-a6874831d44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-25' and (text() = '20068713 - Security Hatch No.10 (Slave)' or . = '20068713 - Security Hatch No.10 (Slave)')]</value>
      <webElementGuid>9bf6caea-9aed-4cef-9c1d-1a1a7165ae44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
