<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_20119680 - Washwater UV Panel No.1 Slave</name>
   <tag></tag>
   <elementGuidId>df97d69f-7f62-4a16-b2cf-ea9bb39fa650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-id-50']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-50</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '20119680 - Washwater UV Panel No.1 Slave' or . = '20119680 - Washwater UV Panel No.1 Slave')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>961a8ab4-e069-447a-b649-570fdfc172e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>0cce486a-a4bd-4318-b554-5604ae31f72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-item-wrapper ui-state-active</value>
      <webElementGuid>8a87177e-643f-4615-a11c-1009e13c516f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-50</value>
      <webElementGuid>4b57367a-3bc5-4fe2-b9a0-93ba869e7ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20119680 - Washwater UV Panel No.1 Slave</value>
      <webElementGuid>e61b68f8-ca35-49dd-a3ab-3dd12d7e14de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-50&quot;)</value>
      <webElementGuid>dd0197f0-decf-4143-af42-3fb37c3bdf05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ui-id-50']</value>
      <webElementGuid>e865c8e4-59cd-4414-90a5-9e3193ddbb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-41']/li[7]/div</value>
      <webElementGuid>29bb46ec-ada3-46dc-9c8c-4963dc364cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CWI Ancillaries (Valves Hydrants etc)'])[4]/following::div[28]</value>
      <webElementGuid>ce5ee0be-7606-4a10-9c63-3f0eae09c265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WWNI Sludge Treatment Facilities'])[2]/following::div[30]</value>
      <webElementGuid>7f2ade54-a4ed-44a9-8827-f6d875dc814c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[14]/li[7]/div</value>
      <webElementGuid>fcecccf2-cc39-4144-bd72-90000d28ada4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ui-id-50' and (text() = '20119680 - Washwater UV Panel No.1 Slave' or . = '20119680 - Washwater UV Panel No.1 Slave')]</value>
      <webElementGuid>20f812d4-28fe-4686-9208-1d4bd36421cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
