<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Cancel_icon-ok</name>
   <tag></tag>
   <elementGuidId>13920832-7270-47ef-99b8-a537e1fb4173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k-bottom-main-buttons-inner > button[name=&quot;D113995&quot;] > i.icon-ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form719685']/div[2]/div[4]/div/div/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>90def5bc-5523-4c92-a975-506e4afe979d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-ok</value>
      <webElementGuid>44ea2ee7-52c7-4e27-a7d0-9d4bb0062765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form719685&quot;)/div[@class=&quot;container k-view-body&quot;]/div[@class=&quot;k-bottom-main-buttons-wrapper&quot;]/div[@class=&quot;k-bottom-main-buttons&quot;]/div[@class=&quot;k-bottom-main-buttons-inner&quot;]/button[@class=&quot;btn btn-default&quot;]/i[@class=&quot;icon-ok&quot;]</value>
      <webElementGuid>47d010be-e8ad-45a8-92f4-5e0c89dc294b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form719685']/div[2]/div[4]/div/div/button[2]/i</value>
      <webElementGuid>dd5e5626-0c0f-4fad-9cbf-8b9436e4152d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button[2]/i</value>
      <webElementGuid>abdb1cca-910d-4bad-baff-7c685bdf2c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
