<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CURR_icon-hand-right k-icon-button</name>
   <tag></tag>
   <elementGuidId>28e38739-8f16-42bb-9f4f-b22413a0fa69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='RR720384:11']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5982417f-0c24-40b5-923b-0ccb40546c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-hand-right k-icon-button</value>
      <webElementGuid>0a537de9-43e7-482c-a9e1-620d9e6ff91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RR720384:11&quot;)/i[@class=&quot;icon-hand-right k-icon-button&quot;]</value>
      <webElementGuid>44577834-0c1c-4ee0-b3e4-e65af11232b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='RR720384:11']/i</value>
      <webElementGuid>696a7568-cb5c-4021-9eda-57d2c72b7bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/span/span/a/i</value>
      <webElementGuid>2ab683af-fd13-49da-a13a-05c6d646894f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
