<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_CURR_icon-hand-right k-icon-button_1</name>
   <tag></tag>
   <elementGuidId>7f8a4180-8515-4d6c-b167-85bb79be69c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='RR720552:9']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c54c0d86-1b19-48e5-9793-21f23527ddb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-hand-right k-icon-button</value>
      <webElementGuid>754b180a-d314-4028-8744-a08933089d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RR720552:9&quot;)/i[@class=&quot;icon-hand-right k-icon-button&quot;]</value>
      <webElementGuid>ef04c627-7b8b-4c40-b981-eabcee58163b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='RR720552:9']/i</value>
      <webElementGuid>631f0f85-9b15-4689-9eb3-ed606e7c88bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/span/span/a/i</value>
      <webElementGuid>c4af4502-991b-4535-ae76-1925fe0133c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
