<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Refresh</name>
   <tag></tag>
   <elementGuidId>5b886f7f-b8ed-4ed3-94b9-d60f0209266c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-menu-navbar-collapse-1']/ul[2]/li[3]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-refresh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7db0d503-77e4-4c95-aee4-e8dd65869b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-refresh</value>
      <webElementGuid>7fc3ad08-8f51-4f98-92ea-9eac7e3a2695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>refresh page</value>
      <webElementGuid>9022716a-8825-48c2-bd87-6f465e6891eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu-navbar-collapse-1&quot;)/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[3]/a[@class=&quot;js-onclick-refresh&quot;]/i[@class=&quot;icon-refresh&quot;]</value>
      <webElementGuid>05ec540e-3e69-4199-a09b-f9a5b27f58f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu-navbar-collapse-1']/ul[2]/li[3]/a/i</value>
      <webElementGuid>e7e6ede1-0577-4d33-87ac-f7e570577def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/i</value>
      <webElementGuid>8d93ee34-e84e-4e26-81b7-124fbff3eb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'refresh page']</value>
      <webElementGuid>f45319a5-6597-483d-ad74-1addd7ed494a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
