<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Toggle navigation_borderpic</name>
   <tag></tag>
   <elementGuidId>2b749c0c-7e45-40c9-891f-ccb251d379b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#borderpic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='borderpic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0ef0b6f7-563a-4577-9781-ba06165d9fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>borderpic</value>
      <webElementGuid>1cd9a07c-a642-4bb5-9d0e-61164509f9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www0.datb.net/dcwwimtest290170/pub/ag1007200000.png</value>
      <webElementGuid>efa82dea-6375-4827-ba5e-1df95881e70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Homepage</value>
      <webElementGuid>84b8609c-3146-40ca-9489-c52f36a27649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Homepage</value>
      <webElementGuid>4a1ea748-0ea0-4488-90d9-a6d539351244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loadingsrc</name>
      <type>Main</type>
      <value>pub/ag1007200001.png</value>
      <webElementGuid>5eeb20db-d54e-4665-a027-1137293376cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;borderpic&quot;)</value>
      <webElementGuid>6ab50974-8bd7-4357-8f17-4d91132ccabc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='borderpic']</value>
      <webElementGuid>f16e8b58-9ba6-486d-bec3-a4831c87639d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v717989:0']/div/div/a/img</value>
      <webElementGuid>ba67999c-9e64-4e38-a603-e19abb7f478a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Homepage']</value>
      <webElementGuid>ef59c913-53da-400a-80d6-9ad7e017e943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>144e825f-a556-4910-8e84-1c98097708e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'borderpic' and @src = 'https://www0.datb.net/dcwwimtest290170/pub/ag1007200000.png' and @alt = 'Homepage' and @title = 'Homepage']</value>
      <webElementGuid>be2c3e0b-6b8d-4ca6-8049-098f7cf2fadc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
