<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Toggle navigation_borderpic_1</name>
   <tag></tag>
   <elementGuidId>af443f95-5ca5-49f0-a4ad-fac817ce7968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#borderpic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='borderpic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5a4df615-41c1-43ba-8f54-e19dfbd9f210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>borderpic</value>
      <webElementGuid>c34bf09e-8bf5-4f44-a71c-c2782f0344e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>pub/ag1007200000.png</value>
      <webElementGuid>179ac4d2-004f-4f29-8f4d-ef2360eaaeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Homepage</value>
      <webElementGuid>c2cb7e9d-48f4-4651-ac46-a43113fcfadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Homepage</value>
      <webElementGuid>264a1aa3-9ff6-4671-a1e6-f9884a1baf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loadingsrc</name>
      <type>Main</type>
      <value>pub/ag1007200001.png</value>
      <webElementGuid>e4ed2fd4-4d02-44cd-93f7-704acc30a27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;borderpic&quot;)</value>
      <webElementGuid>4123186a-bbb1-4bbb-b04b-0e5d39a93b83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='borderpic']</value>
      <webElementGuid>a9dd56ba-0199-415b-aa1b-6aea6b44e96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v717989:1']/div/div/a/img</value>
      <webElementGuid>3d8347e8-f0e4-45a3-be47-7d18bbc4bd10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Homepage']</value>
      <webElementGuid>4e295047-508e-4bef-aac3-fd6e1c92656e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8b0f8c42-b628-4db2-a063-a052ab53366d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'borderpic' and @src = 'pub/ag1007200000.png' and @alt = 'Homepage' and @title = 'Homepage']</value>
      <webElementGuid>0fcdfd2e-c543-45f8-b54a-e77f1261c8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
