<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Title_F100089</name>
   <tag></tag>
   <elementGuidId>f93feb7b-676a-464b-94db-f378edc8a1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IDv719154_F100089']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IDv719154_F100089</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @placeholder = 'required' and @name = 'F100089']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5fb1574-ace6-4e66-a2cf-a96bd975e5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b38a812c-1ed0-436f-afdd-2eeee88cba7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>02ea381a-bd96-41a5-9fbf-b0d0cd46d88b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3005</value>
      <webElementGuid>40325368-cb8f-4db7-819e-81f2c233e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f3952cd4-d424-4b75-bc52-1e3923427bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-regex</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>7ba04ec7-2ae3-4e71-8bcb-9228a0ae0520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F100089</value>
      <webElementGuid>033860fe-5b69-40b3-b17f-62acee5d33fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IDv719154_F100089</value>
      <webElementGuid>0f38fcac-ed0d-4e34-bbc2-5eed66bd2d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>18f770dd-ae86-4d45-9cc4-26ee9e6cc17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-onchange-setTabRqrd form-control k-required</value>
      <webElementGuid>6260ad56-2b13-45d2-80af-5d839e528e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-events-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>139aa3f0-6643-4ba5-a023-371dc75592b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IDv719154_F100089&quot;)</value>
      <webElementGuid>f534fb6b-ddb4-4f45-b6da-b973f6022fa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IDv719154_F100089']</value>
      <webElementGuid>b232108f-24f0-434a-8cd5-aae489a8330b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form719154']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>08f55248-9400-4133-b7d6-b565859f1e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d1fc6799-cf28-441b-88cd-65bbb0f3edd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'required' and @name = 'F100089' and @id = 'IDv719154_F100089']</value>
      <webElementGuid>8d277535-c29f-4607-bef0-a6520c6c9702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
