<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Investment area_F103966_autocomplete</name>
   <tag></tag>
   <elementGuidId>fb37510b-46e3-4ec3-8d5b-cd3d2b2201f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;F103966_autocomplete&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='F103966_autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56dbb168-fdb6-456b-9260-a9b92721d2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3009</value>
      <webElementGuid>0d574b36-a5a8-49be-bf60-888c79b88bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F103966_autocomplete</value>
      <webElementGuid>aafe7781-7a0c-49dd-922e-d39b94928781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6bc2797b-3687-4af2-aa13-5b6c93d5144a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>b411f853-8d08-440c-b3c0-12a4dbab3f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-custom-combobox-input k-required form-control k-required-not-set js-onchange-onblurgo ui-autocomplete-input</value>
      <webElementGuid>e9de2091-5006-4bed-952e-56b8c6179c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0725c9d3-7e32-4d26-8b44-d332918b3fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-events-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ec2069a0-96c4-4d5b-8d63-3d20efe08617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form719154&quot;)/div[@class=&quot;container k-view-body is-fixed&quot;]/section[@class=&quot;k-tab&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;k-field-ctrl&quot;]/div[@class=&quot;k-select k-select-fontawesome form-control&quot;]/span[@class=&quot;k-custom-combobox&quot;]/input[@class=&quot;k-custom-combobox-input k-required form-control k-required-not-set js-onchange-onblurgo ui-autocomplete-input&quot;]</value>
      <webElementGuid>abab084a-d4a3-4bb2-bd6a-600fb7cbb09c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='F103966_autocomplete']</value>
      <webElementGuid>b4668828-1256-4b81-a46d-9714fd01ba9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form719154']/div[2]/section/div[2]/div/div/div/span/input</value>
      <webElementGuid>f7d22703-e234-466e-9c63-d8ebecfbcf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
      <webElementGuid>0c527787-264b-47a9-8dd7-eec489840285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'F103966_autocomplete' and @placeholder = 'required']</value>
      <webElementGuid>96dce6d7-b734-4504-b669-f1924fde4815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
