<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PIN code</name>
   <tag></tag>
   <elementGuidId>57f39b86-841c-40ba-bdb7-438edfe245e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='F53113']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#F53113</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(@title, 'Space character not allowed')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>704eda59-c660-4172-ac3d-c41481b58fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6ee073c6-89b3-4d25-8206-b372428752b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e83044ab-df14-4585-a059-72171217c928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3611ebda-436c-4f72-9035-597b5d97ecda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>8ce14f59-8454-4390-859f-ce5b39567e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2001</value>
      <webElementGuid>7669f333-7b05-447f-821a-a996709de9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[^ ]*$</value>
      <webElementGuid>48f6ff03-6994-4a39-8e09-9a1330077a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Space character not allowed</value>
      <webElementGuid>fe972cf7-6113-4126-871d-59d44c707113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-regex</name>
      <type>Main</type>
      <value>[^ ]</value>
      <webElementGuid>a4a1ff6a-9692-4dd0-9d03-8c7e5f291afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F53113</value>
      <webElementGuid>27e3335b-97bf-4829-b3e6-2c220d93db29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>F53113</value>
      <webElementGuid>e224c31b-ee8a-4867-9835-a896c39a89de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3efa973e-d3d2-43b8-8566-5282d8d8c5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-onchange-setTabRqrd form-control</value>
      <webElementGuid>532c501f-0146-42f1-9cae-85317053f61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-events-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a6c6914-6d57-4ca7-b265-90eaf47800fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;F53113&quot;)</value>
      <webElementGuid>261b6457-6076-44f1-a93d-2c9165d12453</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='F53113']</value>
      <webElementGuid>cf97e97c-bf14-4533-81d4-f250b0dbe6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form418821']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>740f4b8a-63be-42bb-a835-6ed96e3add30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>98ddf0bf-4c11-41d4-834f-6f40df9df52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'Space character not allowed' and @name = 'F53113' and @id = 'F53113']</value>
      <webElementGuid>eceb4512-baf8-4ba5-8eb0-29b870dadd23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
