<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asset location_F113942_autocomplete</name>
   <tag></tag>
   <elementGuidId>c56cf600-bab9-4727-8b4a-03eb1c2ce7b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;F113942_autocomplete&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='F113942_autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9fe7d4c0-150e-4121-9764-e65f743c3ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4006</value>
      <webElementGuid>dea6d656-dcb9-4a3f-ac99-c933bd2b0a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F113942_autocomplete</value>
      <webElementGuid>681c056a-d2aa-4ac2-bd1a-baf6bbb3cb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>339bbbf2-4f2b-4b1d-b9ac-3bda61e665b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-custom-combobox-input k-required form-control js-onchange-onblurgo ui-autocomplete-input</value>
      <webElementGuid>7de5b78b-6b5d-4207-a766-10437278792e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>34ff856f-9c55-49e9-b16c-1b74e0bf3446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-events-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d344e09-3275-4af7-a25d-81ed0b794841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form719685&quot;)/div[@class=&quot;container k-view-body&quot;]/div[@class=&quot;form-group form-inline k-has-top-decor&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;k-field-set&quot;]/div[@class=&quot;k-select k-select-fontawesome form-control&quot;]/span[@class=&quot;k-custom-combobox&quot;]/input[@class=&quot;k-custom-combobox-input k-required form-control js-onchange-onblurgo ui-autocomplete-input&quot;]</value>
      <webElementGuid>750b7270-fbbe-44cf-9e0a-d7b8d3aba913</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='F113942_autocomplete']</value>
      <webElementGuid>132113d5-8cf3-4612-ba51-7d8a3daaf2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form719685']/div[2]/div[2]/div/div/div/span/input</value>
      <webElementGuid>2b71386a-ce8b-4586-b206-e977eb600d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/span/input</value>
      <webElementGuid>1dac1702-1ac1-4d33-9ef6-068e32dcd8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'F113942_autocomplete']</value>
      <webElementGuid>01bee288-22bf-4015-bdc9-3e697b2cd4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
