<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Mitigation_F103508</name>
   <tag></tag>
   <elementGuidId>3418389b-6b9d-40ae-915b-8bc5cee84a30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#F103508</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='F103508']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0be77059-503f-4791-a553-ad8540ca13a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-memofield-maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>8a529d2f-c49b-4197-b544-a6064cbf018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-memofield-minrows</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>617bcf38-e7d6-43e5-8b92-4e551c7d36e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textarea</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d6ae323-bc09-47be-97af-5efb14a3ed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>F103508</value>
      <webElementGuid>5f97405e-8ff2-4e44-915d-edcdec4b4a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F103508</value>
      <webElementGuid>82af2e00-a90a-4777-bbd2-6cc56853f09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3017</value>
      <webElementGuid>c4b93ded-4fe9-4095-a331-c97428b37a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>47cf5544-778b-4412-bae9-00949348fa96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control k-textarea js-onkeypress-memoFieldPress js-onchange-setTabRqrd k-required ui-resizable</value>
      <webElementGuid>c3c99eed-d75b-4101-9f0c-f69c85ed5f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;F103508&quot;)</value>
      <webElementGuid>2fad79bd-516f-48e1-bcb0-b44e4459a99e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='F103508']</value>
      <webElementGuid>5efab82f-ada8-43c4-a6e6-6da058856b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form719154']/div[2]/section[2]/div[4]/div/div/div/textarea</value>
      <webElementGuid>5d687182-3ae6-469a-b641-6b2391f96def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div[4]/div/div/div/textarea</value>
      <webElementGuid>70dffcf4-e43a-455f-bb13-8ca2c046630f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'F103508' and @name = 'F103508' and @placeholder = 'required']</value>
      <webElementGuid>c4ae69ee-6ccf-4ae6-a1b9-82f9373a0b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
