trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/TS2 - Gats by" -browserType="Chrome" -executionProfile="default" -apiKey="f42f0470-19df-42a9-b9a5-641afaa1f1df" -orgID=482208 --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
    xvfbConfiguration: '-s "-screen 0 1024x768x24"'
  env:
    JAVA_HOME: $(JAVA_HOME_8_X64)
    PATH: $(JAVA_HOME_8_X64)/bin:$(PATH)
