<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Count of Solutions_icon-caret-right k-toggle k-icon-button-keyboard k-icon-button</name>
   <tag></tag>
   <elementGuidId>923ccd07-4f38-43f7-9602-f8086cb4e12d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v290685tab100017']/div/h2/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#v290685tab100017 > div.col-sm-12 > h2.k-heading-toggle.k-heading-topborder > i.icon-caret-right.k-toggle.k-icon-button-keyboard.k-icon-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ae4917b6-1ed4-4373-9c67-8baa205dffc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-caret-right k-toggle k-icon-button-keyboard k-icon-button</value>
      <webElementGuid>e6ed91e4-366b-4096-9f69-ab3740a5b19a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-go</name>
      <type>Main</type>
      <value>292821</value>
      <webElementGuid>34026c04-e414-4512-a73b-339b14437113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2031</value>
      <webElementGuid>89722b4d-61ba-42a7-951f-408e79b79144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v290685tab100017&quot;)/div[@class=&quot;col-sm-12&quot;]/h2[@class=&quot;k-heading-toggle k-heading-topborder&quot;]/i[@class=&quot;icon-caret-right k-toggle k-icon-button-keyboard k-icon-button&quot;]</value>
      <webElementGuid>3819379a-f2b4-445b-977a-67763d8c5ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v290685tab100017']/div/h2/i</value>
      <webElementGuid>f9a32617-ec45-4b66-9410-37e08a17854e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[8]/div/div/h2/i</value>
      <webElementGuid>ff7c0fa2-a1ef-4507-a253-008a9105d268</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
