<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Docs_icon-caret-right k-toggle k-icon-button-keyboard k-icon-button</name>
   <tag></tag>
   <elementGuidId>e4b98896-05a8-474f-85b0-91f599b789b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v290685tab100006']/div/h2/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#v290685tab100006 > div.col-sm-12 > h2.k-heading-toggle.k-heading-topborder > i.icon-caret-right.k-toggle.k-icon-button-keyboard.k-icon-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>45877b2f-a906-42a3-8ce5-2d03bdcfb260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-caret-right k-toggle k-icon-button-keyboard k-icon-button</value>
      <webElementGuid>d42f5f90-9dab-4194-bc32-52cf04e8f76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-go</name>
      <type>Main</type>
      <value>292829</value>
      <webElementGuid>fff77e80-ba99-44ef-b34d-048b3ce69403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2035</value>
      <webElementGuid>6fc25fca-4122-4024-a6bb-e83da77e6e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v290685tab100006&quot;)/div[@class=&quot;col-sm-12&quot;]/h2[@class=&quot;k-heading-toggle k-heading-topborder&quot;]/i[@class=&quot;icon-caret-right k-toggle k-icon-button-keyboard k-icon-button&quot;]</value>
      <webElementGuid>6d8f1b19-86e6-4866-9845-644637a052b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v290685tab100006']/div/h2/i</value>
      <webElementGuid>61532809-00af-4be5-8f5f-fbbdc4197622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[12]/div/div/h2/i</value>
      <webElementGuid>1e410b9f-9e27-4b90-9598-a7e51b16ad33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
