<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_F102815</name>
   <tag></tag>
   <elementGuidId>afb5d16d-292c-447f-ab85-c833297918c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'F102815']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/form/div[2]/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IDv291504_F102815</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e4d2cee-c0ed-42cf-8b6c-3ca9601e627c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cdcf9b1-cbf5-4b7c-ab18-f8ae65a347a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>74</value>
      <webElementGuid>fa34ff4b-8a36-4081-a30a-5d989c4bbd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3005</value>
      <webElementGuid>157d7be2-979f-4f5b-b88c-9160b60f82f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>02962e6e-0720-4fdb-b799-6191b372d5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-regex</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>95f9aa46-2e1b-4aa5-a637-6c0a4a9d043f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>F102815</value>
      <webElementGuid>1363a820-237b-4fea-b625-fc7f5af1b80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IDv291504_F102815</value>
      <webElementGuid>0604a338-ab50-4cdd-8b14-4af02460d77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>3ed09f9e-4d59-4b78-a164-440fd810b26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-onchange-setTabRqrd form-control k-required</value>
      <webElementGuid>c99b8da4-860c-4a8e-a79d-5635e6a980d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-k-events-added</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55d562f3-5f95-4e0c-985e-bb2e837e8abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[2]/div/div/input</value>
      <webElementGuid>90683a1b-bc5a-4b61-a43e-0f6294735b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IDv291504_F102815']</value>
      <webElementGuid>97b56948-a5e7-4e1a-bd09-6c2088fa5698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form291504']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>f4c5a831-0af3-426d-817c-1af37b8fc090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[2]/div[2]/div/div/input</value>
      <webElementGuid>f3c7f86d-4b12-4156-af38-d44c2c8fa9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'required' and @name = 'F102815' and @id = 'IDv291504_F102815']</value>
      <webElementGuid>dfdc5a7e-7ff4-44d4-ba6b-c01aedfd71e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
