<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Browse. or drag</name>
   <tag></tag>
   <elementGuidId>88c3d1db-6f96-498f-ac3b-2f9c4c4b42ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(text() = 'Browse... or drag ' or . = 'Browse... or drag ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form291504']/div[2]/div[4]/div/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.k-drop-target-browse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d25e294-8d63-42c0-b4b4-dfb177e4975c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-drop-target-browse</value>
      <webElementGuid>1b84df8c-292c-4018-91bd-cc809789ee7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Browse...</value>
      <webElementGuid>c4f222b4-3f14-46b6-9070-81053fe676a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath2</name>
      <type>Main</type>
      <value>id(&quot;form291504&quot;)/div[@class=&quot;container k-view-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;k-field-ctrl&quot;]/label[@class=&quot;btn btn-default k-drop-target&quot;]/span[@class=&quot;k-drop-target-browse&quot;]</value>
      <webElementGuid>93a1cb45-064b-4f26-af42-9f62a4855b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[(text() = 'Browse... or drag ' or . = 'Browse... or drag ')]</value>
      <webElementGuid>4530462b-548e-4d54-a7f6-c0703026eb78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form291504']/div[2]/div[4]/div/div/label/span</value>
      <webElementGuid>263512a3-3f0e-4ea0-a896-a722544d80f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[2]/following::span[1]</value>
      <webElementGuid>69276ccd-2fb0-4327-ab79-07e82db86041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website URL'])[1]/following::span[1]</value>
      <webElementGuid>1e069bef-9a77-45a0-a323-1d1f3979adb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload'])[1]/preceding::span[3]</value>
      <webElementGuid>a5496339-2269-46ee-9723-1187fb04606e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browse...']/parent::*</value>
      <webElementGuid>0bb68393-2b72-4e58-83bf-cef3fb755ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>054d910c-51e6-4385-91b5-ddc5f35c3d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Browse... or drag ' or . = 'Browse... or drag ')]</value>
      <webElementGuid>0ef8bcc3-9565-418e-a623-b2ee924accdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
